### ISSUE TITLE
Doesn't work on a secure page

### ISSUE THREAD

**Issue by lcamacho** [EricssonResearch/openwebrtc-browser-extensions#8]
HI, I tried with the simple gum example https://webrtc.github.io/samples/src/content/getusermedia/gum/ but on console I see the request to localhost gets blocked.

``[blocked] The page at https://webrtc.github.io/samples/src/content/getusermedia/gum/ was not allowed to run insecure content from http://localhost:10717/owr.js.
``

**Comment by stefhak** [comment]
This is fixed now (but note that you also need to update OpenWebRTC). Closing - re-open if it does not work for you.
